# Generated by Django 5.1.1 on 2026-01-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('url', models.URLField()),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('planta', models.CharField(blank=True, max_length=100, null=True)),
                ('antiguedad', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(max_length=300)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('inmobiliaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.inmobiliaria')),
            ],
        ),
    ]
